SELECT TABLE_NAME FROM TABS;

SELECT * FROM USER_INFO;
SELECT * FROM CONTENT_INFO;
SELECT * FROM CONTENT_VIEW;
SELECT * FROM CONTENT_BACKUP_VIEW;
SELECT * FROM COMMENTS;
SELECT * FROM LIKES;
SELECT * FROM FOLLOW;

DESC USER_INFO;
DESC CONTENT_INFO;
DESC CONTENT_BACKUP;
DESC COMMENTS;
DESC LIKES;

SELECT * FROM CONTENT_VIEW ORDER BY UPDATED_DATE DESC;

COMMIT;