SELECT TABLE_NAME FROM TABS;

SELECT * FROM USER_INFO;
SELECT NOTICE_BOARD, WRITER, CONTENT_NAME, CONTENT_CODE, UPDATED_DATE, LIKES, COMMENTS FROM CONTENT_INFO ORDER BY CONTENT_CODE ASC;
SELECT * FROM COMMENTS;
SELECT * FROM LIKES;

DESC USER_INFO;
DESC CONTENT_INFO;
DESC CONTENT_BACKUP;
DESC COMMENTS;
DESC LIKES;

COMMIT;